### ISSUE TITLE
Timestamp overlay

### ISSUE THREAD

**Issue by kielnino** [geeksville/Micro-RTSP#14]
Hi, is there a possibility to add the current timestamp to the streamed video?

**Comment by Net-time** [comment]
Anything is possible but without RTC and even less FPS probably not feasible.
I suggest you restream it with Vlc or ffmpeg and add timestamp.

**Comment by Hcreak** [comment]
> Anything is possible but without RTC and even less FPS probably not feasible. I suggest you restream it with Vlc or ffmpeg and add timestamp.

I want to overlay 
text on the screen to make the  OSD. The text does not require timeliness. Is this feasible?
